#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
bash $HOME/.screenlayout/monitor.sh

pgrep pcmanfm || pcmanfm -d &
pgrep picom || picom -b &
pgrep dunst || dunst &
pgrep plank || plank &
pgrep nm-applet || nm-applet &
pgrep blueman-applet || blueman-applet &
nitrogen --restore

xinput set-prop 10 315 1 &
xinput set-prop 10 323 1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap           7
bspc config top_padding          30

bspc config focused_border_color '#eeeeee'
bspc config normal_border_color '#444444'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a Pavucontrol state=floating
bspc rule -a Screenkey manage=off

bash ~/.config/polybar/polybarbspwm.sh &
