#!/usr/bin/env bash
hc() {
    herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#5A8E3A'
hc keyunbind --all
Mod=Mod4

## AUTOSTART APPLICATIONS
###########################
$HOME/.config/herbstluftwm/lasttag.sh &
$HOME/.config/herbstluftwm/unminimize.sh
$HOME/.screenlayout/monitor.sh &

# pgrep pcmanfm           || pcmanfm --desktop &
pgrep picom             || picom -b &
pgrep lxpolkit          || lxpolkit &
pgrep dunst             || dunst &
pgrep plank             || plank &
pgrep nm-applet         || nm-applet &
pgrep blueman-applet    || blueman-applet &
pgrep flameshot         || flameshot &
nitrogen --restore

xinput set-prop 11 323 1 &
xinput set-prop 11 322 1 &
xinput set-prop 11 330 1 &
xinput set-prop 11 331 1 &


## SYSTEM KEYBINDINGS
#######################

hc keybind $Mod-Shift-e             quit
hc keybind $Mod-Shift-r             reload

hc keybind $Mod-q                   close
hc keybind $Mod-Shift-q             remove

hc keybind XF86MonBrightnessUp      spawn   light -A 5
hc keybind XF86MonBrightnessDown    spawn   light -U 5
hc keybind XF86AudioRaiseVolume     spawn   pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind XF86AudioLowerVolume     spawn   pactl set-sink-volume @DEFAULT_SINK@ -5%
hc keybind XF86AudioMute            spawn   pactl set-sink-mute 0 toggle


## APPLICATIONS
################
hc keybind $Mod-t                   spawn   kitty
hc keybind $Mod-b                   spawn   firefox
hc keybind $Mod-f                   spawn   pcmanfm
hc keybind $Mod-d                   spawn   rofi -modi drun -show drun -config $HOME/.config/rofi/launcher.rasi

## NAVIGATION
###############
hc keybind $Mod-h                   focus left
hc keybind $Mod-j                   focus down
hc keybind $Mod-k                   focus up
hc keybind $Mod-l                   focus right

hc keybind $Mod-Shift-h             shift left
hc keybind $Mod-Shift-j             shift down
hc keybind $Mod-Shift-k             shift up
hc keybind $Mod-Shift-l             shift right

hc keybind $Mod-period              use_index   +1
hc keybind $Mod-comma               use_index   -1
hc keybind $Mod-Shift-period        chain , move_index +1 , use_index +1
hc keybind $Mod-Shift-comma         chain , move_index -1 , use_index -1

hc keybind $Mod-BackSpace           use_previous
hc keybind $Mod-Shift-BackSpace     chain , use_previous , bring $(herbstclient attr clients.focus.winid)
hc keybind $Mod-Tab                 cycle_all       +1
hc keybind $Mod-Shift-Tab           cycle_all       -1


## LAYOUT
###########
hc set default_frame_layout         max
hc set tree_style '╾│ ├└╼─┐'

hc keybind $Mod-u                   split bottom    0.5
hc keybind $Mod-o                   split right     0.5
hc keybind $Mod-Return              split explode

resizestep=0.02
hc keybind $Mod-Control-h           resize left +$resizestep
hc keybind $Mod-Control-l           resize right +$resizestep
hc keybind $Mod-Control-j           resize down +$resizestep
hc keybind $Mod-Control-k           resize up +$resizestep

hc keybind $Mod-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-s floating toggle 
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical max grid    \
               , cycle_layout +1
hc keybind $Mod-m set_attr clients.focus.minimized true
hc keybind $Mod-Shift-m jumpto last-minimized

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc unrule --all      # clear rules
hc rule focus=on
hc rule index=e
hc rule switchtag=on
hc rule floatplacement=center
hc rule tabbed_max=true
hc rule raise_on_focus=true
hc rule fixedsize floating=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class=Blueman-manager floating=on
hc rule class=Pavucontrol floating=on
hc rule class=Protonvpn floating=on


## TAG SETTINGS
#################
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout max
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done


## THEME
##########
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

red="#EC5F67"
cyan="#5F8787"
redorange="#d64937"
white="#e7e8eb"
bblack="#707880"
bwhite="#FFFFFF"
transparent="#00000000"

# Titles
##########
hc attr theme.title_color           $redorange
hc attr theme.title_height          14
hc attr theme.title_when            multiple_tabs
hc attr theme.title_font            'Noto Sans:size=10:weight=bold'
hc attr theme.title_depth           4

# Frame
#########
hc set smart_window_surroundings    on
hc set smart_frame_surroundings     on
hc set show_frame_decorations       'focused_if_multiple'

hc set window_border_inner_width    0
hc set window_gap                   4
hc set frame_gap                    4
hc set frame_padding                0

hc set frame_bg_transparent         on
hc set frame_border_width           4
hc set frame_border_active_color    $redorange
hc set frame_border_normal_color    $transparent
hc set frame_normal_opacity = 0

hc attr theme.border_width          4
hc attr theme.floating.border_width 4

hc attr theme.active.color          $redorange
hc attr theme.normal.color          $transparent
hc attr theme.urgent.color          $red

for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done


## MONITORS AND PANEL
######################
hc unlock
hc detect_monitors

panel=~/.config/polybar/polybarhlwm.sh
[ -x "$panel" ] || panel=~/.config/polybar/polybarhlwm.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
